### ISSUE TITLE
feature request: free as separate button

### ISSUE THREAD

**Issue by NeonLightning** [Tackyou/gameminer-autojoin#2]
i'm not sure if when you set it to join min of above 0 will it still join the 0 ones because i'd like to set mine to 5+ but also the 0's

**Comment by Tackyou** [comment]
Hm, no it doesn't.
But I get your point, I think about adding a button like "always join 0 coal/gold giveaways"

Any suggestion for the text on the button?

**Comment by Tackyou** [comment]
The update is out now, Version 1.3.2 - thanks for your suggestion!
